use_frameworks!

target 'Example-iOS' do
  platform :ios, '14.0'

  pod 'Sentinel', :path => '../'
  pod 'Sentinel/EmailSender', :path => '../'


  target 'Sentinel_Tests' do
    inherit! :search_paths
  end
end

target 'MacOSExample' do
  platform :osx, '12.0'

  pod 'Sentinel', :path => '../'
end
