---
:language: swift
:bundles:
- :name: Sentinel
  :reference: ".sentinel"
  :assetsSearchPath: "*.xcassets"
  :outputSourcePathImages: "Sentinel/Classes/Core/UIImageExtension.swift"
:app_name: Sentinel
