import UIKit

// THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
// swiftlint:disable file_length type_body_length line_length superfluous_disable_command
extension UIImage {
	enum Sentinel {}
}

extension UIImage.Sentinel {

	static var performance: UIImage { return UIImage(named: "performance", in: .sentinel, compatibleWith: nil)! }
	static var tools: UIImage { return UIImage(named: "tools", in: .sentinel, compatibleWith: nil)! }
	static var permissions: UIImage { return UIImage(named: "permissions", in: .sentinel, compatibleWith: nil)! }
	static var device: UIImage { return UIImage(named: "device", in: .sentinel, compatibleWith: nil)! }
	static var application: UIImage { return UIImage(named: "application", in: .sentinel, compatibleWith: nil)! }
}
